version: '2'

services:

  zookeeper1:
    image: zookeeper
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      INIT_DAEMON_STEP: setup_zookeeper
    volumes:
      - ~/pilot-sc4/zookeeper/conf/zoo.cfg:/zookeeper-3.4.9/conf/zoo.cfg
      - ~/pilot-sc4/zookeeper/datadir/:/zookeeper-3.4.9/datadir/
    networks:
      - pilot-sc4

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.56.101"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181" 
      KAFKA_CREATE_TOPICS: "taxi:1:1"
      INIT_DAEMON_STEP: setup_kafka
    networks:
      - pilot-sc4 

  flink-master:
    image: bde2020/flink-master
    hostname: flink-master
    container_name: flink-master
    domainname: hadoop
    networks:
     - pilot-sc4
    environment:
      INIT_DAEMON_STEP: setup_flink
    ports:
     - "8080:8080"
     - "8081:8081"

  flink-worker:
    image: bde2020/flink-worker
    hostname: flink-worker
    container_name: flink-worker
    domainname: hadoop
    networks: 
     - pilot-sc4
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master

  ###
  # mu.semte.ch stack
  ###

  integratorui:
    image: bde2020/integrator-ui:0.4.3
    volumes:
      - ./config/integrator:/app/config
    environment:
      VIRTUAL_HOST: example.big-data-europe.eu

  monitor:
    image: bde2020/pipeline-monitor-frontend:0.2.2
    links:
      - identifier:backend
    environment:
      VIRTUAL_HOST: monitor.example.big-data-europe.eu

  identifier:
    image: semtech/mu-identifier:1.0.0

  dispatcher:
    image: semtech/mu-dispatcher:1.0.1
    volumes:
      - ./config:/config

  database:
    image: tenforce/virtuoso:1.0.0-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
    ports:
      - "8890:8890"
    volumes:
      - ./data/db:/data

  pipeline:
    image: bde2020/mu-pipeline-service:0.1.0

  initdaemon:
    image: bde2020/mu-init-daemon-service:0.1.0

networks:
  pilot-sc4:
    external: true
