version: '2'

services:

  zookeeper1:
    image: zookeeper
    container_name: zookeeper1
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
    volumes:
      - ~/pilot-sc4/zookeeper/conf/zoo.cfg:/zookeeper-3.4.9/conf/zoo.cfg
      - ~/pilot-sc4/zookeeper/datadir/:/zookeeper-3.4.9/datadir/
    networks:
      - pilot-sc4

  kafka1:
    image: wurstmeister/kafka
    container_name: kafka1 
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "192.168.56.101"
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper1:2181" 
      KAFKA_CREATE_TOPICS: "taxi:1:1"
    networks:
      - pilot-sc4 

  flink-master:
    image: bde2020/flink-master
    hostname: flink-master
    container_name: flink-master
    domainname: hadoop
    networks:
     - pilot-sc4
    ports:
     - "8080:8080"
     - "8081:8081"

  flink-worker:
    image: bde2020/flink-worker
    hostname: flink-worker
    container_name: flink-worker
    domainname: hadoop
    networks: 
     - pilot-sc4
    environment:
      - FLINK_MASTER_PORT_6123_TCP_ADDR=flink-master


networks:
  pilot-sc4:
    external: true
